Practical Linear Algebra Without Knowing Anything
-------------------------------------------------------------------------

For the flying car nanodegree, it is helpful to be up to speed on Linear Algebra, what it is and how it works. However it is possible to get by just by knowing a few things:

## Nomenclature
 - vectors :  an one dimensional array
    <pre>
        [1,2,3,4]
    </pre>

 - matrix : an array type data structure with multiple rows and multiple columns. 
     - described as MxN where M is number of rows and N is number of columns
     - square matrix : M and N are equal
     <pre>
     3x3 matrix
     +-------+
     | 1 2 3 |
     | 4 5 6 |
     | 7 8 9 |
     +-------+
     2x3 matrix
     +-------+
     | 1 2 3 |
     | 4 5 6 |
     +-------+
     3x2 matrix (3 rows, 2 columns
     +-----+
     | 1 2 |
     | 4 5 |
     | 7 8 |
     +-----+
     
     </pre>
 - a matrix can have more than 2 dimensions, but that is uncommon in the flying car world.  What matters for programming  is the shape.

### Numpy
In math, a distinction is made between row and column vectors. In Numpy there is no distinction. Vectors are not 'row' or 'column', they are just arrays with a shape. The shape matters when performing operations on them. Same goes for Matrices. Its important to understand the shapes of arrays in your program and when a particular shape is required. 


In [77]:
import numpy as np

# define a row vector
r = np.array([1,2,3,4])
print(f'r : {r.shape}\n{r}')
c = np.array([[1],[2],[3],[4]])
print(f'c : {c.shape}\n{c}')


r : (4,)
[1 2 3 4]
c : (4, 1)
[[1]
 [2]
 [3]
 [4]]


## Global Numpy Array Functions

In Numpy, Vectors and Matrices are objects of type'ndarray's. Typically just called 'array's when describing them.
Numpy arrays can be created in several ways. There is a mapping directly between a Python list and a Numpy array. Sometimes Numpy will implicitly cast a list to a numpy array, but not always. The following are some of the array creation routines that are global to the numpy package.

If you don't know linear algebra at all or only a little, for the flying car program  you don't need to know things like 'how to traponse a matrix', 'how to do a dot product', 'how to multiple two matrices', 'how to invert a matrix', etc. Numpy will do if for you. You just need to know when to use what, the behavior of the functions, their constraints and what certain error outputs mean.

Note : by default array elements will be float64 unless otherwise specified with the 'dtype' argument.
 
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

 - np.array(list) : create array from Python list . takes the shape of the list
 - np.asarray(object) : create array from something that can be indexed, such as tuples
 - np.zeros(tuple specifying shape) : an array of the specified shape populated with all zeros
 - np.ones(tuple specifying shape) : an array of the specified shape populated with all ones
 - np.indentity(n) : create an identity matrix, a square array with ones on the diagonal and zeros elsewhere
 - np.eye(n,m) : create a 2D array of N rows and M columns, with ones on the diagonal and zeros elsewhere. not technically an identity matrix. 
 
## ndarray Common Object Functions, Methods and Attributes

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html?highlight=ndarray#numpy.ndarray

Numpy ndarrays are Python objects with a number of built in methods. Many of these operations do the same thing that can be accomplished by applying a numpy global function, but in the more object oriented style. usually more concise also.

NOTE : numpy function try to optimize data usage by sometimes returning a 'view' of an array rather than modifying the original array or returning a new array. Usually this doesn't matter and you can use the 'view' just like its an array. But be aware if you change the original, the view will change too. This is unfamiliar to those used to a more functional style where mutation is frowned on and functions always return new objects. Some functions modify the array itself, and some return a new array. So if it matters, check the specific documentation.
 
 - a = np.array(....)
 - SHAPE : get the shape of an array. this is used all the time and also helps debugging when shapes don't match up like in matrix multiplcation
     - a = np.zeros((3,2))  create a matrix with 3 rows, 2 columns, all zeros
     - a = a.reshape((2,3)) change to 2 rows, 3 columns
     - a = np.reshape((6))  change to 1 row of 6 elements
 - COPY : make a copy of an array. this sometimes matters because some functions (see transpose) give a view of an array rather than a new array. 
     - b = np.copy(a)
 - RESHAPE : change the shape of an array. the total number of elements must be the same. this is used a lot
     - a.reshape(tuple with new shape)
     - np.reshape(a, tuple with new shape)
 - TRANPOSE : returns the transpose form of the original array
     - np.transpose(a)
     - a.transpose()
     - a.T
 - SQUEEZE : remove one dimensional elements from an array. modifies the original array. a limited case of 'reshape' 
     - a.squeeze()
     - np.squeeze(a)
 - INVERT and PSEUDOINVERT
     - np.linalg.inv(a) : multiplicative inverse (must be a square array)
     - np.linalg.pinv(a) : computes Penrose-Moore pseudo inversion (durr?). used for least squares. don't ask me what this means except if you are doing a least squares problem where the something isn't square you can still use this. 
  - DOT PRODUCT : multipy a vector or matrix by a 1D vector. Don't use for matrix * matrix
     - np.dot(a,b)
  - MATMUL : multiple two matrices. If matrix sizes are NxM * MxP, returns a matrix with shape NxP. Generally requires that  format. That is, if NxM * QxR, M must equal Q. but there are exceptions with matmul so check the docs if there is any questions. Python 3.5 and later included the infix @ operator for matrix multiplication.  In Python, matrix multiplications operate right to left. 
     - np.matmul(a,b)
     


In [78]:
# NDARRAY METHODS USED A LOT
a = np.array([1,2,3,4])
print("COPY")
b = a.copy();
a[0] = 8;
print(f'{a},{b}')

print("-----------------")
print("RESHAPE")
a = np.zeros((3,2))
print(f'a {a.shape}\n{a}')
a = a.reshape((2,3))
print(f'a {a.shape}\n{a}')
a = a.reshape((6))
print(f'a {a.shape}\n{a}')

print("-----------------")
print("TRANPOSE")
a = np.array([1,2,3,4])
print(a.transpose())
b = np.array([[1,2,3],[4,5,6]])
c = b.transpose()
print(f'original\n{b}\ntransposed\n{c}')
b[0,1] = 8
# NOTICE THAT THE TRANSPOSITION IS A VIEW AND IT GETS THE CHANGE TO b
print(f'original\n{b}\ntransposed\n{c}')

print("-----------------")
print("SQUEEZE")
a = np.array([[1],[2],[3],[4]])
b = a.squeeze()
print(f'a\n{a}\nb\n{b}')

print("-----------------")
print("INVERT and PSEUDOINVERT")
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.linalg.inv(a)
c = np.linalg.pinv(a)
print(f'a\n{a}\ninv\n{b}\npinv{c}\n')
a = np.array([[1,2,3],[4,5,6]])
print(f'a\n{a}\n')
try:
    b = np.linalg.inv(a)
except Exception as err:
    print('error :', err)
c = np.linalg.pinv(a)
print(f'pinv{c}\n')

print("-----------------")
print("DOT AND MATMAUL")
a = np.array([1,2,3])
b = np.ones((3,3))
c = a.dot(b)
print(f'a.dot(b)\n{a}\n{b}\n{c}')
a = np.ones((2,3))
b = np.full((3,2),2)
c = a @ b
print(f'a @ b\n{a}\n{b}\n{c}')
c = np.matmul(a,b)
print(f'np.matmul(a,b)\n{a}\n{b}\n{c}')


COPY
[8 2 3 4],[1 2 3 4]
-----------------
RESHAPE
a (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
a (2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
a (6,)
[0. 0. 0. 0. 0. 0.]
-----------------
TRANPOSE
[1 2 3 4]
original
[[1 2 3]
 [4 5 6]]
transposed
[[1 4]
 [2 5]
 [3 6]]
original
[[1 8 3]
 [4 5 6]]
transposed
[[1 4]
 [8 5]
 [3 6]]
-----------------
SQUEEZE
a
[[1]
 [2]
 [3]
 [4]]
b
[1 2 3 4]
-----------------
INVERT and PSEUDOINVERT
a
[[1 2 3]
 [4 5 6]
 [7 8 9]]
inv
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
pinv[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  1.38777878e-16  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]

a
[[1 2 3]
 [4 5 6]]

error : Last 2 dimensions of the array must be square
pinv[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

-----------------
DOT AND MATMAUL
a.dot(b)
[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]
 [1.

## Least Squares

One of the most common uses of linear algebra is to compute the coefficients of a linear equation given a set of data samples and a set of truth data (same number of each)
example:
you want to compute c1,c2 and c3 where  c1 * ax + c2 * ay + c3 * az = m
you are given a set of samples of ax,ay,az and m. say the sets are 2000 samples long. in this case then, you would need
an array of vectors C of shape(2000,3) = 2000 rows, each of 3 columns representing the vector of samples taken. Also, you need a 1D array M of truth data representing the value of the equation given the 3 sample. This array will be shape (2000,).

M = f(C)

Then you just do 
c = np.linalg.lstsq(M,C). this will output a matrix of size 2x3.

In [79]:
# M is the truth data
M = np.random.randn(2000,1)
# C are the measurements
C = np.random.randn(2000,4)
L = np.linalg.lstsq(M,C,rcond=None)
print(L[0])
print("------------")
# to get a scaling and cross couple matrix across 3 axes, do this
# M is the truth data
M = np.random.randn(2000,4)
# C are the measurements
C = np.random.randn(2000,3)
# scaling_matrix
S = np.zeros((3,4))
# for the measurements for each axis
for i in range(3):
    L = np.linalg.lstsq(M,C[:,i],rcond=None)[0]
    S[i,:] = L
print(S)
# first 3 columns are scale/cross couple and last column is bias
    

[[ 0.02587122 -0.0158962   0.00267546 -0.02165443]]
------------
[[ 0.03034572 -0.03079982  0.00594598  0.00418251]
 [ 0.007833    0.00036779 -0.05663834 -0.00078283]
 [-0.01137922  0.02383629 -0.00512109  0.0145692 ]]
